version: '3.1'
services:
  web:
    container_name: monitoring-server
    image: webapp
    build: /MonitoringApplication/
    depends_on:
      - meter-db
    ports:
      - "8080:8080"
    environment:
      - DRIVER_NAME=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://meter-db:5432/meterdb
      - DATASOURCE_USER=admin
      - DATASOURCE_PASSWORD=admin

  meter-db:
    image: postgres:16-alpine
    container_name: meter-db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=meterdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
